### ISSUE TITLE
unknown keyword: default_value_dynamic

### ISSUE THREAD

**Issue by magneticrob** [fastlane-community/fastlane-plugin-firebase_app_distribution#21]
Hi,

I've just opened an issue on the main fastlane project and just realised it may well be better fixed here: https://github.com/fastlane/fastlane/issues/15602

Everything works fine up until the firebase_app_distribution step. I then get the following:

```
[16:23:06]: ---------------------------------------
[16:23:06]: --- Step: firebase_app_distribution ---
[16:23:06]: ---------------------------------------
[16:23:06]: You passed invalid parameters to 'firebase_app_distribution'.
[16:23:06]: Check out the error below and available options by running `fastlane action firebase_app_distribution`
```

with the following stack trace:

```
/Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane_core/lib/fastlane_core/configuration/config_item.rb:58:in `initialize': [!] unknown keyword: default_value_dynamic (ArgumentError)
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-firebase_app_distribution-0.1.4/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:65:in `new'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-firebase_app_distribution-0.1.4/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:65:in `available_options'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/configuration_helper.rb:4:in `parse'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:236:in `block (2 levels) in execute_action'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `chdir'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/one_off.rb:41:in `run'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/one_off.rb:22:in `execute'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:192:in `block (2 levels) in run'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
from /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/bin/fastlane:20:in `<top (required)>'
from /Users/xxx/.fastlane/bin/bundle/bin/fastlane:22:in `load'
from /Users/xxx/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

I'm so close! Any help would be appreciated.

**Comment by tonybaroneee** [comment]
Hey @magneticrob! Check out https://github.com/fastlane-community/fastlane-plugin-firebase_app_distribution/issues/17 for a similar report. Thanks!
